# Generated by Django 5.2 on 2025-04-30 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Character_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='cast/')),
            ],
        ),
        migrations.CreateModel(
            name='generes_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='generes/')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nav_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_name', models.CharField(max_length=255)),
                ('Movie_about', models.TextField()),
                ('img', models.ImageField(upload_to='Movies/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_name', models.CharField(max_length=250)),
                ('Movie_rating', models.FloatField()),
                ('img', models.ImageField(upload_to='Movies/')),
                ('movie_poster', models.ImageField(default='00', upload_to='Poster/')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('movie_type', models.CharField(default='popular', max_length=250)),
                ('age', models.IntegerField(default=0)),
                ('country', models.CharField(default='India', max_length=100)),
                ('Revenue', models.IntegerField(default=0)),
                ('Runtime', models.IntegerField(default=0)),
                ('description', models.TextField(default='No description available')),
                ('cast', models.ManyToManyField(related_name='movies', to='mainapp.actor')),
                ('genere', models.ManyToManyField(related_name='generes', to='mainapp.genre')),
                ('language', models.ManyToManyField(related_name='language', to='mainapp.language')),
            ],
        ),
    ]
