# Generated by Django 5.2 on 2025-04-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='languages_name',
            new_name='name',
        ),
    ]
