# Generated by Django 5.2 on 2025-04-30 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_languages_name_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_card',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
