# Generated by Django 5.2 on 2025-05-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_movie_card_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_card',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
