# Generated by Django 5.2 on 2025-05-16 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_movie_card_trailer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_name', models.CharField(max_length=250)),
                ('Series_rating', models.FloatField()),
                ('Series_img', models.ImageField(upload_to='Series_Movies/')),
                ('Series_poster', models.ImageField(default='00', upload_to='Poster/')),
                ('Series_release_date', models.DateField(default=datetime.date.today)),
                ('Series_type', models.CharField(default='popular', max_length=250)),
                ('Series_age', models.IntegerField(default=0)),
                ('Series_country', models.CharField(default='India', max_length=100)),
                ('Series_Revenue', models.IntegerField(default=0)),
                ('Series_Runtime', models.IntegerField(default=0)),
                ('Series_description', models.TextField(default='No description available')),
                ('Series_trailer_url', models.URLField(blank=True, null=True)),
                ('Series_cast', models.ManyToManyField(related_name='Series_movies', to='mainapp.actor')),
                ('Series_genere', models.ManyToManyField(related_name='Series_generes', to='mainapp.genre')),
                ('Series_language', models.ManyToManyField(related_name='Series_language', to='mainapp.language')),
            ],
        ),
    ]
