# Generated by Django 5.2 on 2025-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_series_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_card',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
